### ISSUE TITLE
不显示下载链接

### ISSUE THREAD

**Issue by xuqingfeng** [seekerlee/Sound-Pirate#22]
chrome version: 49
os: OS X

试了网易云音乐，豆瓣 fm

**Comment by spacewander** [comment]
试下这个分支能不能解决问题？
https://github.com/spacewander/Sound-Pirate

在 chrome://extensions/ 页面下选“开发者模式”就能安装插件代码。

**Comment by xuqingfeng** [comment]
@spacewander 网易云音乐可以显示，豆瓣 fm 依然不可以

**Comment by spacewander** [comment]
我又推送了一些新改动，更新下代码看看？

**Comment by xuqingfeng** [comment]
@spacewander 可以下载 :+1: 但格式是 MP4 可以改成 MP3 吗？

**Comment by spacewander** [comment]
豆瓣FM播放的音乐格式是mp4的（虽然很奇怪不过源文件就是如此）。

**Comment by spacewander** [comment]
如果没有更多问题的话，我们先关掉这个issue，有问题再重开。
