### ISSUE TITLE
不能下载www.app-echo.com的音乐

### ISSUE THREAD

**Issue by sutking** [seekerlee/Sound-Pirate#24]
作者有没时间给解决一下啊？拜托喽~~~~

**Comment by spacewander** [comment]
看了下，要下载是可以的，不过比较复杂。到时候开发完之后，你能帮忙测试下吗？

**Comment by sutking** [comment]
嗯，发完这条issue之后我自己也看了下，这个网站的音频文件格式都是*.ts的，而且貌似（之所以说貌似是因为没有普遍调查，不敢妄下结论）单个文件时长都小于等于30秒，也就是说时间较长的音频文件都是分段的，下载之后还涉及到一个文件合并的问题。另外一个问题就是*.ts文件看起来很不常用，支持它的播放器并不多，而且到目前为止我还没有找到可用的格式转换器…
能给我测试的机会我当然十分荣幸，非常愿意！

**Comment by sutking** [comment]
细想了下，“声海盗”仅仅是一个为下载页面中音频文件的浏览器插件，要合并所下载的文件和转换格式貌似超出了声海盗的定位，并且较编写初衷有所偏离，因此，只要可以下载被分段的“*.ts”文件就功成名就了吧😉

**Comment by spacewander** [comment]
看到你这么及时的回复，我就放心了。
你试试这个分支上的代码：https://github.com/seekerlee/Sound-Pirate/tree/support_echo
下载下来是m3u8文件。

**Comment by sutking** [comment]
能不能教我怎么用？😂😂😂这么不专业实在抱歉，见笑了…😂😂

**Comment by spacewander** [comment]
1. `git clone https://github.com/seekerlee/Sound-Pirate -b support_echo --depth 1`下载代码。
2. 打开chrome://extensions/
3. 勾选右上角的“开发者模式”
4. 点击“加载已解压的扩展程序...”按钮，选择`$PATH/Sound-Pirate/src`。请把`$PATH`替换成第一步下载的代码所在的文件夹。记得先禁用从Chrome商店安装的版本，以免冲突。

有什么不明白的尽管@我。

**Comment by sutking** [comment]
刚才测试下载了两个音频播放页面的m3u8文件，真的好用到没朋友！！👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼真的是32个赞哦！接下来再试用些时日，看看会不会遇到某些特殊情况的比较少见的bug喽~有问题及时反馈你！再次感谢你！

**Comment by spacewander** [comment]
欢迎深入测试哈！:smile: 
我个人只在首页试了下，如果有什么问题就@我吧。

**Comment by sutking** [comment]
好的，没有问题👌

**Comment by seekerlee** [comment]
已经 merge 到 master 分支，最新版 1.9.0 应该解决了这个问题。
