### ISSUE TITLE
更新Google浏览器版本右下角不出现图标

### ISSUE THREAD

**Issue by yiba13** [seekerlee/Sound-Pirate#25]
刚更新了Google浏览器版本到58.0.3029.81，发现右下角链接图标不出现了。重下了插件，发现还是解决不了问题。

**Comment by spacewander** [comment]
@yiba13 
新版本的 Chrome 引入了 break change，刚刚我更新了代码进行了适配。
试下代码库里最新的代码能否解决你的问题？（需要在 `chrome://extensions/` 中启用开发者模式）

**Comment by yiba13** [comment]
完美解决了问题！

**Comment by spacewander** [comment]
@seekerlee 
是时候发布一个兼容 Chrome 58 的新版本了 :smile:

**Comment by seekerlee** [comment]
感谢！本周末我搞下。

**Comment by seekerlee** [comment]
已经提交给 Google，一个小时之内会发布成功。如果有问题 reopen 这个。
