### ISSUE TITLE
网易云音乐失效

### ISSUE THREAD

**Issue by suxiaogang** [seekerlee/Sound-Pirate#28]

**Comment by spacewander** [comment]
@suxiaogang 
网易云音乐改用 websocket 的方式逐段逐段加载音乐，不再像之前那样直接加载整个音乐文件了。关于这个问题，我目前也想不出什么好办法。

**Comment by suxiaogang** [comment]
一个切入点? 在chrome里设置media query为iPad时还有效

**Comment by suxiaogang** [comment]
这两天好像又正常了... @spacewander
